// This file is generated by next-typesafe-url
// Do not edit this file directly.

// @generated
// prettier-ignore
/* eslint-disable */

declare module "@@@next-typesafe-url" {
  import type { InferRoute, StaticRoute } from "next-typesafe-url";

  interface DynamicRouter {
  
  }

  interface StaticRouter {
    "/agents": StaticRoute;
    "/dashboard": StaticRoute;
    "/projects": StaticRoute;
    "/projects/[id]": StaticRoute;
    "/settings": StaticRoute;
    "/templates": StaticRoute;
    "/workflows/active": StaticRoute;
    "/workflows/history": StaticRoute;
    "/workflows": StaticRoute;
    "/": StaticRoute;
  }
}
