// This file is generated by next-typesafe-url
// Do not edit this file directly.

// @generated
// prettier-ignore
/* eslint-disable */

declare module "@@@next-typesafe-url" {
  import type { InferRoute, StaticRoute } from "next-typesafe-url";

  interface DynamicRouter {
    "/projects": InferRoute<import("./app/(app)/projects/route-type").RouteType>;
    "/projects/[id]": InferRoute<import("./app/(app)/projects/[id]/route-type").RouteType>;
  }

  interface StaticRouter {
    "/agents": StaticRoute;
    "/dashboard": StaticRoute;
    "/settings": StaticRoute;
    "/templates": StaticRoute;
    "/workflows/active": StaticRoute;
    "/workflows/history": StaticRoute;
    "/workflows": StaticRoute;
    "/": StaticRoute;
  }
}
