import {
  Bot,
  Bug,
  Clock,
  FileText,
  FolderKanban,
  GitCompare,
  GitPullRequest,
  History,
  LayoutDashboard,
  MessageCircle,
  PanelLeft,
  Play,
  Plus,
  Settings,
  Terminal,
} from 'lucide-react';
import { $path } from 'next-typesafe-url';

import type { Command } from './types';

export const COMMANDS: Array<Command> = [
  // Go to
  {
    category: 'Go to',
    execute: ({ navigate }) => navigate($path({ route: '/dashboard' })),
    icon: LayoutDashboard,
    id: 'goto-dashboard',
    keywords: ['home', 'overview'],
    label: 'Dashboard',
  },
  {
    category: 'Go to',
    execute: ({ navigate }) => navigate($path({ route: '/projects' })),
    icon: FolderKanban,
    id: 'goto-projects',
    keywords: ['workspace'],
    label: 'Projects',
  },
  {
    category: 'Go to',
    execute: ({ navigate }) => navigate($path({ route: '/agents' })),
    icon: Bot,
    id: 'goto-agents',
    keywords: ['bot', 'claude'],
    label: 'Agents',
  },
  {
    category: 'Go to',
    execute: ({ navigate }) => navigate($path({ route: '/templates' })),
    icon: FileText,
    id: 'goto-templates',
    keywords: ['prompt'],
    label: 'Templates',
  },
  {
    category: 'Go to',
    execute: ({ navigate }) => navigate('/chat'),
    icon: MessageCircle,
    id: 'goto-chat',
    keywords: ['conversation', 'message'],
    label: 'Chat',
  },
  {
    category: 'Go to',
    execute: ({ navigate }) => navigate('/changes'),
    icon: GitCompare,
    id: 'goto-changes',
    keywords: ['diff', 'code review'],
    label: 'Changes',
  },
  {
    category: 'Go to',
    execute: ({ navigate }) => navigate('/pulls'),
    icon: GitPullRequest,
    id: 'goto-pulls',
    keywords: ['pr', 'pull request', 'github'],
    label: 'Pull Requests',
  },
  {
    category: 'Go to',
    execute: ({ navigate }) => navigate($path({ route: '/settings' })),
    icon: Settings,
    id: 'goto-settings',
    keywords: ['preferences', 'config'],
    label: 'Settings',
  },
  {
    category: 'Go to',
    execute: ({ navigate }) => navigate($path({ route: '/workflows/active' })),
    icon: Play,
    id: 'goto-workflows-active',
    keywords: ['running'],
    label: 'Active Workflows',
  },
  {
    category: 'Go to',
    execute: ({ navigate }) => navigate($path({ route: '/workflows/created' })),
    icon: Clock,
    id: 'goto-workflows-created',
    label: 'Created Workflows',
  },
  {
    category: 'Go to',
    execute: ({ navigate }) => navigate($path({ route: '/workflows/history', searchParams: {} })),
    icon: History,
    id: 'goto-workflows-history',
    keywords: ['past', 'completed'],
    label: 'Workflow History',
  },

  // Create
  {
    category: 'Create',
    execute: ({ requestDialog }) => requestDialog('create-project'),
    icon: Plus,
    id: 'create-project',
    keywords: ['project', 'workspace', 'new'],
    label: 'New Project',
  },
  {
    category: 'Create',
    execute: ({ requestDialog }) => requestDialog('create-agent'),
    icon: Plus,
    id: 'create-agent',
    keywords: ['agent', 'bot', 'new'],
    label: 'New Agent',
  },
  {
    category: 'Create',
    execute: ({ requestDialog }) => requestDialog('create-template'),
    icon: Plus,
    id: 'create-template',
    keywords: ['template', 'prompt', 'new'],
    label: 'New Template',
  },
  {
    category: 'Create',
    execute: ({ navigate }) => navigate('/chat'),
    icon: MessageCircle,
    id: 'create-chat',
    keywords: ['conversation', 'new'],
    label: 'New Chat',
  },

  // Toggle
  {
    category: 'Toggle',
    execute: ({ toggleSidebar }) => toggleSidebar(),
    icon: PanelLeft,
    id: 'toggle-sidebar',
    keywords: ['sidebar', 'panel', 'collapse', 'expand'],
    label: 'Toggle Sidebar',
  },
  {
    category: 'Toggle',
    execute: ({ toggleTerminal }) => toggleTerminal(),
    icon: Terminal,
    id: 'toggle-terminal',
    keywords: ['terminal', 'console', 'shell'],
    label: 'Toggle Terminal',
  },
  {
    category: 'Toggle',
    execute: ({ openDebugWindow }) => openDebugWindow(),
    icon: Bug,
    id: 'open-debug',
    keywords: ['debug', 'logs', 'devtools'],
    label: 'Open Debug Window',
  },
];
