/**
 * IPC Channel Constants
 *
 * Centralized channel definitions for all Electron IPC communication.
 * Follow the naming pattern: `{domain}:{action}` or `{domain}:{subdomain}:{action}`
 *
 * Rules:
 * - Use lowercase with colons as separators
 * - Action names are camelCase
 * - Group related channels under domain objects
 * - Maintain alphabetical order within objects
 * - Export as `const` for type inference
 */
export const IpcChannels = {
  agent: {
    activate: 'agent:activate',
    copyToProject: 'agent:copyToProject',
    create: 'agent:create',
    createOverride: 'agent:createOverride',
    deactivate: 'agent:deactivate',
    delete: 'agent:delete',
    duplicate: 'agent:duplicate',
    export: 'agent:export',
    exportBatch: 'agent:exportBatch',
    get: 'agent:get',
    import: 'agent:import',
    list: 'agent:list',
    move: 'agent:move',
    reset: 'agent:reset',
    update: 'agent:update',
  },
  agentActivity: {
    getByStepId: 'agentActivity:getByStepId',
    getByWorkflowId: 'agentActivity:getByWorkflowId',
  },
  agentHook: {
    create: 'agentHook:create',
    delete: 'agentHook:delete',
    list: 'agentHook:list',
    update: 'agentHook:update',
  },
  agentSkill: {
    create: 'agentSkill:create',
    delete: 'agentSkill:delete',
    list: 'agentSkill:list',
    setRequired: 'agentSkill:setRequired',
    update: 'agentSkill:update',
  },
  agentStream: {
    cancel: 'agentStream:cancel',
    getSession: 'agentStream:getSession',
    port: 'agentStream:port',
    start: 'agentStream:start',
  },
  agentTool: {
    allow: 'agentTool:allow',
    create: 'agentTool:create',
    delete: 'agentTool:delete',
    disallow: 'agentTool:disallow',
    list: 'agentTool:list',
    update: 'agentTool:update',
  },
  app: {
    getPath: 'app:getPath',
    getVersion: 'app:getVersion',
  },
  audit: {
    create: 'audit:create',
    export: 'audit:export',
    findByStep: 'audit:findByStep',
    findByWorkflow: 'audit:findByWorkflow',
    list: 'audit:list',
  },
  chat: {
    compactConversation: 'chat:compactConversation',
    copyMessages: 'chat:copyMessages',
    createConversation: 'chat:createConversation',
    createMessage: 'chat:createMessage',
    deleteConversation: 'chat:deleteConversation',
    exportToNewChat: 'chat:exportToNewChat',
    forkConversation: 'chat:forkConversation',
    generateTitle: 'chat:generateTitle',
    getConversation: 'chat:getConversation',
    getTokenEstimate: 'chat:getTokenEstimate',
    listActiveMessages: 'chat:listActiveMessages',
    listConversations: 'chat:listConversations',
    listMessages: 'chat:listMessages',
    restoreMessage: 'chat:restoreMessage',
    revertToMessage: 'chat:revertToMessage',
    searchMessages: 'chat:searchMessages',
    softDeleteMessage: 'chat:softDeleteMessage',
    updateConversation: 'chat:updateConversation',
  },
  clarification: {
    getState: 'clarification:getState',
    retry: 'clarification:retry',
    skip: 'clarification:skip',
    start: 'clarification:start',
    stream: 'clarification:stream',
    submitAnswers: 'clarification:submitAnswers',
    submitEdits: 'clarification:submitEdits',
  },
  debugLog: {
    clearLogs: 'debugLog:clearLogs',
    getLogPath: 'debugLog:getLogPath',
    getLogs: 'debugLog:getLogs',
    getSessionIds: 'debugLog:getSessionIds',
    openDebugWindow: 'debugLog:openDebugWindow',
    openLogFile: 'debugLog:openLogFile',
  },
  dialog: {
    openDirectory: 'dialog:openDirectory',
    openFile: 'dialog:openFile',
    saveFile: 'dialog:saveFile',
  },
  diff: {
    getBranches: 'diff:getBranches',
    getDiff: 'diff:getDiff',
    getFileContent: 'diff:getFileContent',
    getFileDiff: 'diff:getFileDiff',
    getLog: 'diff:getLog',
    getStatus: 'diff:getStatus',
    getWorktreeDiff: 'diff:getWorktreeDiff',
  },
  diffComment: {
    create: 'diffComment:create',
    delete: 'diffComment:delete',
    list: 'diffComment:list',
    listByFile: 'diffComment:listByFile',
    toggleResolved: 'diffComment:toggleResolved',
    update: 'diffComment:update',
  },
  discovery: {
    add: 'discovery:add',
    cancel: 'discovery:cancel',
    delete: 'discovery:delete',
    exclude: 'discovery:exclude',
    getState: 'discovery:getState',
    include: 'discovery:include',
    list: 'discovery:list',
    rediscover: 'discovery:rediscover',
    start: 'discovery:start',
    stream: 'discovery:stream',
    toggle: 'discovery:toggle',
    update: 'discovery:update',
    updatePriority: 'discovery:updatePriority',
  },
  editor: {
    detect: 'editor:detect',
    getPreferred: 'editor:getPreferred',
    getRegistry: 'editor:getRegistry',
    open: 'editor:open',
    setPreferred: 'editor:setPreferred',
  },
  fileExplorer: {
    listDirectory: 'fileExplorer:listDirectory',
    searchFiles: 'fileExplorer:searchFiles',
  },
  fileViewState: {
    getStats: 'fileViewState:getStats',
    list: 'fileViewState:list',
    markUnviewed: 'fileViewState:markUnviewed',
    markViewed: 'fileViewState:markViewed',
  },
  fs: {
    exists: 'fs:exists',
    readDirectory: 'fs:readDirectory',
    readFile: 'fs:readFile',
    stat: 'fs:stat',
    writeFile: 'fs:writeFile',
  },
  github: {
    checkAuth: 'github:checkAuth',
    closePr: 'github:closePr',
    convertToReady: 'github:convertToReady',
    createPr: 'github:createPr',
    createPrComment: 'github:createPrComment',
    detectPrTemplate: 'github:detectPrTemplate',
    getDeployments: 'github:getDeployments',
    getPr: 'github:getPr',
    getPrDiff: 'github:getPrDiff',
    getPrDiffParsed: 'github:getPrDiffParsed',
    getRepoInfo: 'github:getRepoInfo',
    listChecks: 'github:listChecks',
    listPrComments: 'github:listPrComments',
    listPrs: 'github:listPrs',
    mergePr: 'github:mergePr',
    pushComment: 'github:pushComment',
    replyToPrComment: 'github:replyToPrComment',
    rerunCheck: 'github:rerunCheck',
    rerunFailedChecks: 'github:rerunFailedChecks',
    syncComments: 'github:syncComments',
    updatePr: 'github:updatePr',
  },
  mcpServer: {
    delete: 'mcpServer:delete',
    detectProjectServers: 'mcpServer:detectProjectServers',
    list: 'mcpServer:list',
    save: 'mcpServer:save',
    toggle: 'mcpServer:toggle',
  },
  planning: {
    approvePlan: 'planning:approvePlan',
    cancel: 'planning:cancel',
    editPlan: 'planning:editPlan',
    getState: 'planning:getState',
    retry: 'planning:retry',
    start: 'planning:start',
    stream: 'planning:stream',
    submitFeedback: 'planning:submitFeedback',
  },
  project: {
    addRepo: 'project:addRepo',
    archive: 'project:archive',
    create: 'project:create',
    delete: 'project:delete',
    deleteHard: 'project:deleteHard',
    get: 'project:get',
    list: 'project:list',
    listFavorites: 'project:listFavorites',
    toggleFavorite: 'project:toggleFavorite',
    unarchive: 'project:unarchive',
    update: 'project:update',
  },
  provider: {
    deleteKey: 'provider:deleteKey',
    getKey: 'provider:getKey',
    list: 'provider:list',
    listConfigured: 'provider:listConfigured',
    setKey: 'provider:setKey',
    validate: 'provider:validate',
  },
  refinement: {
    cancel: 'refinement:cancel',
    getResult: 'refinement:getResult',
    getState: 'refinement:getState',
    regenerate: 'refinement:regenerate',
    retry: 'refinement:retry',
    start: 'refinement:start',
    stream: 'refinement:stream',
  },
  repository: {
    clearDefault: 'repository:clearDefault',
    create: 'repository:create',
    delete: 'repository:delete',
    deleteWithCleanup: 'repository:deleteWithCleanup',
    detectGitInfo: 'repository:detectGitInfo',
    findByPath: 'repository:findByPath',
    findByProject: 'repository:findByProject',
    get: 'repository:get',
    list: 'repository:list',
    preDeleteInfo: 'repository:preDeleteInfo',
    setDefault: 'repository:setDefault',
    update: 'repository:update',
  },
  settings: {
    bulkUpdate: 'settings:bulkUpdate',
    get: 'settings:get',
    getByCategory: 'settings:getByCategory',
    getByKey: 'settings:getByKey',
    list: 'settings:list',
    resetToDefault: 'settings:resetToDefault',
    setValue: 'settings:setValue',
  },
  step: {
    complete: 'step:complete',
    edit: 'step:edit',
    fail: 'step:fail',
    get: 'step:get',
    list: 'step:list',
    regenerate: 'step:regenerate',
    skip: 'step:skip',
    start: 'step:start',
    update: 'step:update',
  },
  store: {
    delete: 'store:delete',
    get: 'store:get',
    set: 'store:set',
  },
  template: {
    activate: 'template:activate',
    create: 'template:create',
    delete: 'template:delete',
    get: 'template:get',
    getPlaceholders: 'template:getPlaceholders',
    incrementUsage: 'template:incrementUsage',
    list: 'template:list',
    update: 'template:update',
    updatePlaceholders: 'template:updatePlaceholders',
  },
  terminal: {
    create: 'terminal:create',
    data: 'terminal:data',
    exit: 'terminal:exit',
    getInfo: 'terminal:getInfo',
    input: 'terminal:input',
    kill: 'terminal:kill',
    listActive: 'terminal:listActive',
    new: 'terminal:new',
    resize: 'terminal:resize',
    toggle: 'terminal:toggle',
  },
  workflow: {
    cancel: 'workflow:cancel',
    create: 'workflow:create',
    delete: 'workflow:delete',
    get: 'workflow:get',
    getConcurrencyStats: 'workflow:getConcurrencyStats',
    getQueuePosition: 'workflow:getQueuePosition',
    getStatistics: 'workflow:getStatistics',
    list: 'workflow:list',
    listHistory: 'workflow:listHistory',
    pause: 'workflow:pause',
    resume: 'workflow:resume',
    start: 'workflow:start',
    update: 'workflow:update',
  },
  workflowRepository: {
    add: 'workflowRepository:add',
    addMultiple: 'workflowRepository:addMultiple',
    list: 'workflowRepository:list',
    remove: 'workflowRepository:remove',
  },
  worktree: {
    cleanup: 'worktree:cleanup',
    create: 'worktree:create',
    get: 'worktree:get',
    getByWorkflowId: 'worktree:getByWorkflowId',
    list: 'worktree:list',
  },
} as const;

/**
 * Type for extracting channel string values for type-safe usage
 */
export type IpcChannel = typeof IpcChannels;
